version: '3.4'
services:
  rdio-downstream:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SYS_FILE_PATH=/systems.json
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - ./systems.json:/systems.json
      - ./tones.json:/tones.json
      - ./custom-scripts/:/custom-scripts/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro